### ISSUE TITLE
"No implicit conversion from nil to integer"

### ISSUE THREAD

**Issue by borisschapira** [GM-Alex/vagrant-winnfsd#35]
```
{path_to_plugin}/lib/vagrant-winnfsd/plugin.rb:60:in `system': no implicit conversion from nil to integer (TypeError)

from {path_to_plugin}/lib/vagrant-winnfsd/plugin.rb:60:in `init_plugin'

from {path_to_plugin}/lib/vagrant-winnfsd/plugin.rb:20:in `block in <class:Plugin>'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:42:in `call'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:42:in `block (2 levels) in run'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:41:in `tap'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:41:in `block in run'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:40:in `map'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:40:in `run'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:187:in `initialize'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:165:in `new'

from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:165:in `<main>'
```

**Comment by borisschapira** [comment]
Sorry, bug already filled in #25
